Prevent compiler from optimizing security checks for hcitols
projectceladon/hcitools pull request #5
Opened 2020-01-14 10:12 UTC by aiswaryacyriac

Adding compiler flags to not optimize on security checks

Tracked-On: OAM-89006
Signed-off-by: Aiswarya Cyriac <aiswarya.cyriac@intel.com>

2020-01-14 10:19 UTC, sysopenci reviewed
Autobuild started from pull-request-changes on this PR.

FAILURE: CheckBug Bad comments/Bugs

For more information, see: /absp/builders/celadon-autobuild/builds/1535

2020-01-16 03:59 UTC, JeevakaPrabu requested changes

2020-01-16 03:59 UTC, JeevakaPrabu commented on Android.mk
> +                -fno-strict-overfloa -fno-delete-null-pointer-checks \
typo -fno-strict-overfloa -> -fno-strict-overflow

2020-01-16 05:13 UTC, sysopenci reviewed
Autobuild started from pull-request-changes on this PR.

FAILURE: Trigger Builds Triggered: build-cel - r1 (celadon_ivi), build-cel - r2 (r2_celadon_ivi) - extra

For more information, see: /absp/builders/celadon-autobuild/builds/1537

2020-01-20 04:11 UTC, JeevakaPrabu approved these changes

2020-01-20 11:13 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-cel - r1 (caas), build-cel - r1 (celadon_ivi), build-cel - r1 (celadon_tablet), build-cel - r1 (cic), build-cel - r2 (r2_celadon_ivi), build-cel - r2 (r2_celadon_tablet) - extra

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/1461

2020-01-21 07:15 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-cel - r1 (caas), build-cel - r1 (celadon_ivi), build-cel - r1 (celadon_tablet), build-cel - r1 (cic), build-cel - r2 (r2_celadon_ivi), build-cel - r2 (r2_celadon_tablet) - extra

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/1464

2020-01-21 09:02 UTC, aprasadd approved these changes

2020-01-21 09:22 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/1465

2020-01-21 09:38 UTC, JeevakaPrabu approved these changes

2020-01-21 09:55 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/1466

2020-01-21 11:02 UTC, sysopenci reviewed
Autobuild started from pull-request-changes on this PR.

Cactus automatically verified this PR.

For more information, see: /absp/builders/celadon-autobuild/builds/1564

2020-01-22 07:52 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/1468

Done by "Cyriac, Aiswarya" <aiswarya.cyriac@intel.com>

2020-01-22 09:30 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/711

Done by "Cyriac, Aiswarya" <aiswarya.cyriac@intel.com>

2020-01-22 12:14 UTC, merged

2020-01-22 12:15 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Cyriac, Aiswarya" <aiswarya.cyriac@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/1413